version: "3.9"

services: 
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/certs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/wordpress:/var/www/html
    depends_on:
      - mariadb
      - wordpress
    networks:
      - wordpress-network
    restart: always


  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - wordpress-network

  wordpress:
    container_name: wordpress
    image: wordpress:php7.4-fpm
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge
