version: "3.9"

services: 
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
      - ./nginx/ssl:/etc/nginx/ssl/
      - ./nginx/default.conf:/etc/nginx/http.d/nginx.conf
    depends_on:
      - wordpress
    networks:
      - wordpress-network
    restart: always

  mariadb:
    container_name: mariadb
    build: ./mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - wordpress-network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./wordpress
    volumes:
      - ./data/wordpress:/var/www/html
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    networks:
      - wordpress-network
    depends_on:
      - mariadb
    restart: always

networks:
  wordpress-network:
    driver: bridge
