version: "3.9"

services: 
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html/wordpress
      - ./nginx/ssl:/etc/nginx/ssl/
      - ./nginx/default.conf:/etc/nginx/http.d/nginx.conf
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./wordpress
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

# Need to change the device path to show /home/tpereira/data in 42 cluster VM
volumes:
  wordpress_vol:
    driver: local
    driver_opts: 
      type: none
      device: /Users/tiago/Desktop/42Cursus/inception/srcs/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
