version: '3'

services:
  nginx:
    build: 
      context: ./srcs/nginx
    ports:
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/certs  # Adjust as needed for your SSL certificates
    networks:
      - app-network

  wordpress:
    image: wordpress:5.7-php7.4-fpm  # Use specific version instead of latest
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress_user  # Replace with your database username
      WORDPRESS_DB_PASSWORD: wordpress_password  # Replace with your database password
      WORDPRESS_DB_NAME: wordpress  # Replace with your database name
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - app-network

  mariadb:
    image: mariadb:10.5  # Use specific version instead of latest
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Replace with your root password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  wordpress_data:
