version: "3.9"

services: 
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
    depends_on:
      - mariadb
      - wordpress
    networks:
      - wordpress-network
    restart: always

  mariadb:
    container_name: mariadb
    build: ./mariadb
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - wordpress-network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./wordpress
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge
