FROM mariadb:10.5

# Copy your custom my.cnf if needed
# COPY ./srcs/mariadb/my.cnf /etc/mysql/my.cnf

# Environment variables are already handled in the docker-compose file

EXPOSE 3306

CMD ["mysqld"]
